language: r
sudo: required

os:
  - linux

r_build_args: --no-build-vignettes --no-manual --no-resave-data
r_check_args: --no-build-vignettes --no-manual

r_binary_packages:
  - Rcpp
  - bigmemory.sri
  - BH
  - devtools
  - roxygen2

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'devtools::install();library(bigmemory);library(methods);devtools::test()'
  - Rscript -e 'library(covr);coveralls()'
