language: r
sudo: required
dist: trusty   
warnings_are_errors: true

before_install: 
  - sudo apt-get install ghostscript

after_success:
  - Rscript -e 'library(covr);coveralls()' 

# TODO: can add build and check args. Also valgrind. See https://github.com/HenrikBengtsson/matrixStats/blob/master/.travis.yml

r:
- release
- devel  

script:
  - R CMD build . --compact-vignettes=both
  - R CMD check *tar.gz --as-cran

# Not cran will run tests skipped on cran
#  Travis is not taking this into account
not_cran: 
- true
- false 

bioc_packages:
- graph
- Rgraphviz

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - _R_CHECK_CRAN_INCOMING_=true
 
# do not build vignettes as that requires Bioc packages such as graph 
# r_build_args: "--no-build-vignettes"
# r_check_args: "--no-build-vignettes --no-manual --as-cran" 
