language: r
sudo: required
dist: trusty 

-r_build_args: --no-build-vignettes --no-manual --no-resave-data
-r_check_args: --no-build-vignettes --no-manual 

after_success:
  - Rscript -e 'library(covr);coveralls()'

## Set up the matrix of different runs
env:
  global:
  - _R_CHECK_CRAN_INCOMING_: TRUE
  matrix:
  - r: release
    not_cran: true
    r_check_args: "--no-manual"
  - r: release
    not_cran: false
    r_check_args: "--no-manual --as-cran"
  - r: devel
    not_cran: true
    r_check_args: "--no-manual"
  - r: devel
    not_cran: false
    r_check_args: "--no-manual --as-cran" 
