language: r
sudo: required
dist: trusty   
warnings_are_errors: true

after_success:
  - Rscript -e 'library(covr);coveralls()' 

r:
- oldrel
- release
- devel  

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - _R_CHECK_CRAN_INCOMING_=true
  
r_build_args: "--no-build-vignettes"
r_check_args: "--no-build-vignettes --no-manual --as-cran" 
