language: r
sudo: required
dist: trusty   

after_success:
  - Rscript -e 'library(covr);coveralls()' 

r:
- oldrel
- release
- devel  

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_= FALSE
  - _R_CHECK_CRAN_INCOMING_: TRUE
  
r_build_args: "--no-build-vignettes"
r_check_args: "--no-build-vignettes --no-manual --as-cran" 
